global:
    mode: global
    metrics:
        request:
            desc: Everytime we received a request, this counter will +1
        response:
            desc: Everytime we send a response, this counter will +1
        latency:
            desc: "This is the sum of the latency for each transaction (unit: micro-second)"
        entity_create:
            desc: The total amount of entities be created
        entity_destroy:
            desc: The total amount of entities be destroyed
        connection_opened:
            desc: The total connections be created
        connection_closed:
            desc: How many connections be destroyed
        uptime:
            desc: System uptime, every second +1
        timer_created:
            desc: How many timers were created
        timer_triggered:
            desc: How many timers were triggered
        timer_canceled:
            desc: How many timers were canceled
        timer_completed:
            desc: How many timers were completed
        timer_delayed:
            desc: "Sum latency (micro-seconds) of all triggered timers"
        srv_iocall:
            desc: How many service iocalls be invoked
        srv_iocall_complete:
            desc: How many service iocalls be completed
        srv_iocall_execute:
            desc: How many service iocalls be executed
        srv_iocall_busy:
            desc: How many service iocalls failed due to service busy
        srv_timer_emit:
            desc: How many timers be emitted
        srv_timer_complete:
            desc: How many timers be completed
        srv_timer_busy:
            desc: How many service timers failed due to service busy
        ep_create:
            desc: How many endpoints be created
        ep_destroy:
            desc: How many endpoints be destroyed
        ep_send:
            desc: How many requests be sent by endpoint
        ep_recv:
            desc: How many responses be received by endpoint
        ep_ok:
            desc: How many ep transactions succeed
        ep_timeout:
            desc: How many ep transactions timed out
        ep_error:
            desc: How many ep transactions encounter error

        log_error_write: true
        log_error_async_push: true
        log_error_async_pop: true
        log_truncated: true
        log_buffer_full: true
        log_buffer_released: true

worker:
    mode: thread
    metrics:
        accept:
            desc: Accept counter (only for accept thread)
        request:
            desc: When the worker thread receive a request, this counter will +1
        response:
            desc: When the worker thread send a response, this coutner will +1
        latency:
            desc: "The sum of the latency for each transaction in the thread (unit: micro-second)"
        entity_create:
            desc: The total amount of entities be created
        entity_destroy:
            desc: The total amount of entities be destroyed
        connection_opened:
            desc: The total count of the connections be hold in this thread
        connection_closed:
            desc: How many connections be destroyed in this thread
        timer_created:
            desc: How many timers be emitted
        timer_triggered:
            desc: How many timers were triggered
        timer_canceled:
            desc: How many timers were canceled
        timer_completed:
            desc: How many timers be completed
        timer_delayed:
            desc: "Sum latency (micro-seconds) of all triggered timers"
        srv_iocall:
            desc: How many service iocalls be invoked
        srv_iocall_complete:
            desc: How many service iocalls be completed
        srv_iocall_execute:
            desc: How many service iocalls be executed
        srv_iocall_busy:
            desc: How many service iocalls failed due to service busy
        srv_timer_emit:
            desc: How many timers be emitted
        srv_timer_complete:
            desc: How many timers be completed
        srv_timer_busy:
            desc: How many service timers failed due to service busy
        ep_create:
            desc: How many endpoints be created
        ep_destroy:
            desc: How many endpoints be destroyed
        ep_send:
            desc: How many requests be sent by endpoint
        ep_recv:
            desc: How many responses be received by endpoint
        ep_ok:
            desc: How many ep transactions succeed
        ep_timeout:
            desc: How many ep transactions timed out
        ep_error:
            desc: How many ep transactions encounter error

