#!/bin/bash

function usage()
{
    echo "usage:"
    echo "  create_workflow -c concurrent -I idl -i enable_stdin -n enable_network -p port"
}

function init()
{
    BIN_PATH=`dirname $0`

    . $BIN_PATH/env.bash
}

function parse_and_run()
{
    # parse the command args
    local args=`getopt -a \
        -o c:i:I:n:p:h \
        -l concurrent:,enable_stdin:enable_network:,idl:,port:,help \
        -n "create_workflow" -- "$@"`

    if [ $? != 0 ]; then
        echo "Error: Invalid parameters" >&2
        usage >&2
        exit 1
    fi

    eval set -- "$args"

    local concurrent="y"
    local idl="example"
    local enable_stdin="n"
    local enable_network="y"
    local port="7758"

    while true; do
        case "$1" in
            -c|--concurrent)
                concurrent=$2
                shift 2;
                ;;
            -i|--enable_stdin)
                enable_stdin=$2
                shift 2;
                ;;
            -n|--enable_network)
                enable_network=$2
                shift 2;
                ;;
            -I|--idl)
                idl=$2
                shift 2;
                ;;
            -p|--port)
                port=$2
                shift 2;
                ;;
            -h|--help)
                shift
                usage
                exit 0
                ;;
            --)
                shift;
                break;
                ;;
            *)
                echo "Error: Invalid parameters $1" >&2
                shift
                usage >&2
                exit 1
                ;;
        esac
    done

    # start to create workflow
    run $concurrent $idl $enable_stdin $enable_network $port
}

function run()
{
    local concurrent="$1"
    local idl="$2"
    local enable_stdin="$3"
    local enable_network="$4"
    local port="$5"

    (
        cd $SKULL_PROJ_NAME

        expect -c "
            spawn skull workflow -a
            expect \"Allow concurrent? (y/n)\" {send \"$concurrent\r\"}
            expect \"Input the IDL name:\" {send \"$idl\r\"}
            expect \"Input Data Source: stdin? (y/n)\" {send \"$enable_stdin\r\"}
            expect \"Input Data Source: Network? (y/n)\" {send \"$enable_network\r\"}
            expect \"Input the port you want (1025-65535):\" {send \"$port\r\"}
            sleep 1
            interact
        "
    )
}

# ----------------- main ------------------
init
parse_and_run $@
