#!/bin/bash

function usage()
{
    echo "usage:"
    echo "  create_module -n name -i workflow_idx -l language"
}

function init()
{
    BIN_PATH=`dirname $0`

    . $BIN_PATH/env.bash
}

function parse_and_run()
{
    # parse the command args
    local args=`getopt -a \
        -o p:d:h \
        -l port:,data:,help \
        -n "mock_ep" -- "$@"`

    if [ $? != 0 ]; then
        echo "Error: Invalid parameters" >&2
        usage >&2
        exit 1
    fi

    eval set -- "$args"

    local port="7760"
    local data="world"

    while true; do
        case "$1" in
            -p|--port)
                port=$2
                shift 2;
                ;;
            -d|--data)
                data=$2
                shift 2;
                ;;
            -h|--help)
                shift
                usage
                exit 0
                ;;
            --)
                shift;
                break;
                ;;
            *)
                echo "Error: Invalid parameters $1" >&2
                shift
                usage >&2
                exit 1
                ;;
        esac
    done

    # start to create module
    run "$port" "$data"
}

function run()
{
    local port="$1"
    local data="$2"

    (
        cd $SKULL_PROJ_NAME

        expect -c "
            spawn nohup bash -c \"echo $data | nc -l 127.0.0.1 $port\" &
            send \"\r\"
        "
    )
}

# ----------------- main ------------------
init
parse_and_run $@
